# eureka consumer

spring:
  application:
    name: eureka-consumer-feign

server:
  port: 16666

eureka:
  client:
    serviceUrl:
      defaultZone: http://127.0.0.1:8881/eureka/

management:
  endpoints:
    web:
      exposure:
        include: ["health","info","hystrix.stream"]