// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: kwmsgcmd.proto

#include "kwmsgcmd.pb.h"

#include <algorithm>

#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/extension_set.h>
#include <google/protobuf/wire_format_lite.h>
#include <google/protobuf/descriptor.h>
#include <google/protobuf/generated_message_reflection.h>
#include <google/protobuf/reflection_ops.h>
#include <google/protobuf/wire_format.h>
// @@protoc_insertion_point(includes)
#include <google/protobuf/port_def.inc>

PROTOBUF_PRAGMA_INIT_SEG
namespace KWMsg {
constexpr ReqCmdExecute::ReqCmdExecute(
  ::PROTOBUF_NAMESPACE_ID::internal::ConstantInitialized)
  : cmd_operator_(&::PROTOBUF_NAMESPACE_ID::internal::fixed_address_empty_string)
  , payload_(&::PROTOBUF_NAMESPACE_ID::internal::fixed_address_empty_string)
  , cmd_(0)
  , world_id_(0)
  , req_id_(int64_t{0}){}
struct ReqCmdExecuteDefaultTypeInternal {
  constexpr ReqCmdExecuteDefaultTypeInternal()
    : _instance(::PROTOBUF_NAMESPACE_ID::internal::ConstantInitialized{}) {}
  ~ReqCmdExecuteDefaultTypeInternal() {}
  union {
    ReqCmdExecute _instance;
  };
};
PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT ReqCmdExecuteDefaultTypeInternal _ReqCmdExecute_default_instance_;
constexpr ReqGmGetPlayerData::ReqGmGetPlayerData(
  ::PROTOBUF_NAMESPACE_ID::internal::ConstantInitialized)
  : data_names_()
  , id_(&::PROTOBUF_NAMESPACE_ID::internal::fixed_address_empty_string)
  , id_type_(0)

  , data_type_(0)

  , req_id_(int64_t{0}){}
struct ReqGmGetPlayerDataDefaultTypeInternal {
  constexpr ReqGmGetPlayerDataDefaultTypeInternal()
    : _instance(::PROTOBUF_NAMESPACE_ID::internal::ConstantInitialized{}) {}
  ~ReqGmGetPlayerDataDefaultTypeInternal() {}
  union {
    ReqGmGetPlayerData _instance;
  };
};
PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT ReqGmGetPlayerDataDefaultTypeInternal _ReqGmGetPlayerData_default_instance_;
constexpr AckGmGetPlayerData::AckGmGetPlayerData(
  ::PROTOBUF_NAMESPACE_ID::internal::ConstantInitialized)
  : data_names_()
  , data_values_()
  , id_(&::PROTOBUF_NAMESPACE_ID::internal::fixed_address_empty_string)
  , req_id_(int64_t{0})
  , id_type_(0)

  , data_type_(0)

  , ret_type_(0)
{}
struct AckGmGetPlayerDataDefaultTypeInternal {
  constexpr AckGmGetPlayerDataDefaultTypeInternal()
    : _instance(::PROTOBUF_NAMESPACE_ID::internal::ConstantInitialized{}) {}
  ~AckGmGetPlayerDataDefaultTypeInternal() {}
  union {
    AckGmGetPlayerData _instance;
  };
};
PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT AckGmGetPlayerDataDefaultTypeInternal _AckGmGetPlayerData_default_instance_;
}  // namespace KWMsg
static ::PROTOBUF_NAMESPACE_ID::Metadata file_level_metadata_kwmsgcmd_2eproto[3];
static const ::PROTOBUF_NAMESPACE_ID::EnumDescriptor* file_level_enum_descriptors_kwmsgcmd_2eproto[3];
static constexpr ::PROTOBUF_NAMESPACE_ID::ServiceDescriptor const** file_level_service_descriptors_kwmsgcmd_2eproto = nullptr;

const ::PROTOBUF_NAMESPACE_ID::uint32 TableStruct_kwmsgcmd_2eproto::offsets[] PROTOBUF_SECTION_VARIABLE(protodesc_cold) = {
  ~0u,  // no _has_bits_
  PROTOBUF_FIELD_OFFSET(::KWMsg::ReqCmdExecute, _internal_metadata_),
  ~0u,  // no _extensions_
  ~0u,  // no _oneof_case_
  ~0u,  // no _weak_field_map_
  PROTOBUF_FIELD_OFFSET(::KWMsg::ReqCmdExecute, cmd_operator_),
  PROTOBUF_FIELD_OFFSET(::KWMsg::ReqCmdExecute, cmd_),
  PROTOBUF_FIELD_OFFSET(::KWMsg::ReqCmdExecute, world_id_),
  PROTOBUF_FIELD_OFFSET(::KWMsg::ReqCmdExecute, payload_),
  PROTOBUF_FIELD_OFFSET(::KWMsg::ReqCmdExecute, req_id_),
  ~0u,  // no _has_bits_
  PROTOBUF_FIELD_OFFSET(::KWMsg::ReqGmGetPlayerData, _internal_metadata_),
  ~0u,  // no _extensions_
  ~0u,  // no _oneof_case_
  ~0u,  // no _weak_field_map_
  PROTOBUF_FIELD_OFFSET(::KWMsg::ReqGmGetPlayerData, id_),
  PROTOBUF_FIELD_OFFSET(::KWMsg::ReqGmGetPlayerData, id_type_),
  PROTOBUF_FIELD_OFFSET(::KWMsg::ReqGmGetPlayerData, data_type_),
  PROTOBUF_FIELD_OFFSET(::KWMsg::ReqGmGetPlayerData, req_id_),
  PROTOBUF_FIELD_OFFSET(::KWMsg::ReqGmGetPlayerData, data_names_),
  ~0u,  // no _has_bits_
  PROTOBUF_FIELD_OFFSET(::KWMsg::AckGmGetPlayerData, _internal_metadata_),
  ~0u,  // no _extensions_
  ~0u,  // no _oneof_case_
  ~0u,  // no _weak_field_map_
  PROTOBUF_FIELD_OFFSET(::KWMsg::AckGmGetPlayerData, id_),
  PROTOBUF_FIELD_OFFSET(::KWMsg::AckGmGetPlayerData, id_type_),
  PROTOBUF_FIELD_OFFSET(::KWMsg::AckGmGetPlayerData, req_id_),
  PROTOBUF_FIELD_OFFSET(::KWMsg::AckGmGetPlayerData, data_type_),
  PROTOBUF_FIELD_OFFSET(::KWMsg::AckGmGetPlayerData, ret_type_),
  PROTOBUF_FIELD_OFFSET(::KWMsg::AckGmGetPlayerData, data_names_),
  PROTOBUF_FIELD_OFFSET(::KWMsg::AckGmGetPlayerData, data_values_),
};
static const ::PROTOBUF_NAMESPACE_ID::internal::MigrationSchema schemas[] PROTOBUF_SECTION_VARIABLE(protodesc_cold) = {
  { 0, -1, sizeof(::KWMsg::ReqCmdExecute)},
  { 10, -1, sizeof(::KWMsg::ReqGmGetPlayerData)},
  { 20, -1, sizeof(::KWMsg::AckGmGetPlayerData)},
};

static ::PROTOBUF_NAMESPACE_ID::Message const * const file_default_instances[] = {
  reinterpret_cast<const ::PROTOBUF_NAMESPACE_ID::Message*>(&::KWMsg::_ReqCmdExecute_default_instance_),
  reinterpret_cast<const ::PROTOBUF_NAMESPACE_ID::Message*>(&::KWMsg::_ReqGmGetPlayerData_default_instance_),
  reinterpret_cast<const ::PROTOBUF_NAMESPACE_ID::Message*>(&::KWMsg::_AckGmGetPlayerData_default_instance_),
};

const char descriptor_table_protodef_kwmsgcmd_2eproto[] PROTOBUF_SECTION_VARIABLE(protodesc_cold) =
  "\n\016kwmsgcmd.proto\022\005KWMsg\"e\n\rReqCmdExecute"
  "\022\024\n\014cmd_operator\030\001 \001(\014\022\013\n\003cmd\030\002 \001(\005\022\020\n\010w"
  "orld_id\030\003 \001(\005\022\017\n\007payload\030\004 \001(\014\022\016\n\006req_id"
  "\030\005 \001(\003\"\244\001\n\022ReqGmGetPlayerData\022\n\n\002id\030\001 \001("
  "\014\022.\n\007id_type\030\002 \001(\0162\035.KWMsg.EGmGetPlayerD"
  "ataIDType\022.\n\tdata_type\030\003 \001(\0162\033.KWMsg.EGm"
  "GetPlayerDataType\022\016\n\006req_id\030\004 \001(\003\022\022\n\ndat"
  "a_names\030\005 \003(\014\"\356\001\n\022AckGmGetPlayerData\022\n\n\002"
  "id\030\001 \001(\014\022.\n\007id_type\030\002 \001(\0162\035.KWMsg.EGmGet"
  "PlayerDataIDType\022\016\n\006req_id\030\003 \001(\003\022.\n\tdata"
  "_type\030\004 \001(\0162\033.KWMsg.EGmGetPlayerDataType"
  "\0223\n\010ret_type\030\005 \001(\0162!.KWMsg.EAckGmGetPlay"
  "erDataRetType\022\022\n\ndata_names\030\006 \003(\014\022\023\n\013dat"
  "a_values\030\007 \003(\014*R\n\024EGmGetPlayerDataType\022\013"
  "\n\007EDT_MIN\020\000\022\020\n\014EDT_PROPERTY\020\001\022\016\n\nEDT_REC"
  "ORD\020\002\022\013\n\007EDT_MAX\020\003*h\n\026EGmGetPlayerDataID"
  "Type\022\013\n\007EIT_MIN\020\000\022\022\n\016EIT_ACCOUNT_ID\020\001\022\022\n"
  "\016EIT_DIGITAL_ID\020\002\022\014\n\010EIT_GUID\020\003\022\013\n\007EIT_M"
  "AX\020\004*\306\001\n\032EAckGmGetPlayerDataRetType\022\020\n\014E"
  "ART_SUCCESS\020\000\022\035\n\031EART_ERR_PLAYER_NOT_EXI"
  "ST\020\001\022\032\n\026EART_ERR_KEY_NOT_EXIST\020\002\022\026\n\022EART"
  "_ERR_DATA_TYPE\020\003\022\024\n\020EART_ERR_ID_TYPE\020\004\022\027"
  "\n\023EART_ERR_DATA_VALUE\020\005\022\024\n\020EART_ERR_UNKN"
  "OWN\020\006B\nZ\010./;KWMsgb\006proto3"
  ;
static ::PROTOBUF_NAMESPACE_ID::internal::once_flag descriptor_table_kwmsgcmd_2eproto_once;
const ::PROTOBUF_NAMESPACE_ID::internal::DescriptorTable descriptor_table_kwmsgcmd_2eproto = {
  false, false, 945, descriptor_table_protodef_kwmsgcmd_2eproto, "kwmsgcmd.proto", 
  &descriptor_table_kwmsgcmd_2eproto_once, nullptr, 0, 3,
  schemas, file_default_instances, TableStruct_kwmsgcmd_2eproto::offsets,
  file_level_metadata_kwmsgcmd_2eproto, file_level_enum_descriptors_kwmsgcmd_2eproto, file_level_service_descriptors_kwmsgcmd_2eproto,
};
PROTOBUF_ATTRIBUTE_WEAK const ::PROTOBUF_NAMESPACE_ID::internal::DescriptorTable* descriptor_table_kwmsgcmd_2eproto_getter() {
  return &descriptor_table_kwmsgcmd_2eproto;
}

// Force running AddDescriptors() at dynamic initialization time.
PROTOBUF_ATTRIBUTE_INIT_PRIORITY static ::PROTOBUF_NAMESPACE_ID::internal::AddDescriptorsRunner dynamic_init_dummy_kwmsgcmd_2eproto(&descriptor_table_kwmsgcmd_2eproto);
namespace KWMsg {
const ::PROTOBUF_NAMESPACE_ID::EnumDescriptor* EGmGetPlayerDataType_descriptor() {
  ::PROTOBUF_NAMESPACE_ID::internal::AssignDescriptors(&descriptor_table_kwmsgcmd_2eproto);
  return file_level_enum_descriptors_kwmsgcmd_2eproto[0];
}
bool EGmGetPlayerDataType_IsValid(int value) {
  switch (value) {
    case 0:
    case 1:
    case 2:
    case 3:
      return true;
    default:
      return false;
  }
}

const ::PROTOBUF_NAMESPACE_ID::EnumDescriptor* EGmGetPlayerDataIDType_descriptor() {
  ::PROTOBUF_NAMESPACE_ID::internal::AssignDescriptors(&descriptor_table_kwmsgcmd_2eproto);
  return file_level_enum_descriptors_kwmsgcmd_2eproto[1];
}
bool EGmGetPlayerDataIDType_IsValid(int value) {
  switch (value) {
    case 0:
    case 1:
    case 2:
    case 3:
    case 4:
      return true;
    default:
      return false;
  }
}

const ::PROTOBUF_NAMESPACE_ID::EnumDescriptor* EAckGmGetPlayerDataRetType_descriptor() {
  ::PROTOBUF_NAMESPACE_ID::internal::AssignDescriptors(&descriptor_table_kwmsgcmd_2eproto);
  return file_level_enum_descriptors_kwmsgcmd_2eproto[2];
}
bool EAckGmGetPlayerDataRetType_IsValid(int value) {
  switch (value) {
    case 0:
    case 1:
    case 2:
    case 3:
    case 4:
    case 5:
    case 6:
      return true;
    default:
      return false;
  }
}


// ===================================================================

class ReqCmdExecute::_Internal {
 public:
};

ReqCmdExecute::ReqCmdExecute(::PROTOBUF_NAMESPACE_ID::Arena* arena)
  : ::PROTOBUF_NAMESPACE_ID::Message(arena) {
  SharedCtor();
  RegisterArenaDtor(arena);
  // @@protoc_insertion_point(arena_constructor:KWMsg.ReqCmdExecute)
}
ReqCmdExecute::ReqCmdExecute(const ReqCmdExecute& from)
  : ::PROTOBUF_NAMESPACE_ID::Message() {
  _internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
  cmd_operator_.UnsafeSetDefault(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited());
  if (!from._internal_cmd_operator().empty()) {
    cmd_operator_.Set(::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::EmptyDefault{}, from._internal_cmd_operator(), 
      GetArenaForAllocation());
  }
  payload_.UnsafeSetDefault(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited());
  if (!from._internal_payload().empty()) {
    payload_.Set(::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::EmptyDefault{}, from._internal_payload(), 
      GetArenaForAllocation());
  }
  ::memcpy(&cmd_, &from.cmd_,
    static_cast<size_t>(reinterpret_cast<char*>(&req_id_) -
    reinterpret_cast<char*>(&cmd_)) + sizeof(req_id_));
  // @@protoc_insertion_point(copy_constructor:KWMsg.ReqCmdExecute)
}

void ReqCmdExecute::SharedCtor() {
cmd_operator_.UnsafeSetDefault(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited());
payload_.UnsafeSetDefault(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited());
::memset(reinterpret_cast<char*>(this) + static_cast<size_t>(
    reinterpret_cast<char*>(&cmd_) - reinterpret_cast<char*>(this)),
    0, static_cast<size_t>(reinterpret_cast<char*>(&req_id_) -
    reinterpret_cast<char*>(&cmd_)) + sizeof(req_id_));
}

ReqCmdExecute::~ReqCmdExecute() {
  // @@protoc_insertion_point(destructor:KWMsg.ReqCmdExecute)
  SharedDtor();
  _internal_metadata_.Delete<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>();
}

void ReqCmdExecute::SharedDtor() {
  GOOGLE_DCHECK(GetArenaForAllocation() == nullptr);
  cmd_operator_.DestroyNoArena(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited());
  payload_.DestroyNoArena(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited());
}

void ReqCmdExecute::ArenaDtor(void* object) {
  ReqCmdExecute* _this = reinterpret_cast< ReqCmdExecute* >(object);
  (void)_this;
}
void ReqCmdExecute::RegisterArenaDtor(::PROTOBUF_NAMESPACE_ID::Arena*) {
}
void ReqCmdExecute::SetCachedSize(int size) const {
  _cached_size_.Set(size);
}

void ReqCmdExecute::Clear() {
// @@protoc_insertion_point(message_clear_start:KWMsg.ReqCmdExecute)
  ::PROTOBUF_NAMESPACE_ID::uint32 cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  cmd_operator_.ClearToEmpty();
  payload_.ClearToEmpty();
  ::memset(&cmd_, 0, static_cast<size_t>(
      reinterpret_cast<char*>(&req_id_) -
      reinterpret_cast<char*>(&cmd_)) + sizeof(req_id_));
  _internal_metadata_.Clear<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>();
}

const char* ReqCmdExecute::_InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) {
#define CHK_(x) if (PROTOBUF_PREDICT_FALSE(!(x))) goto failure
  while (!ctx->Done(&ptr)) {
    ::PROTOBUF_NAMESPACE_ID::uint32 tag;
    ptr = ::PROTOBUF_NAMESPACE_ID::internal::ReadTag(ptr, &tag);
    switch (tag >> 3) {
      // bytes cmd_operator = 1;
      case 1:
        if (PROTOBUF_PREDICT_TRUE(static_cast<::PROTOBUF_NAMESPACE_ID::uint8>(tag) == 10)) {
          auto str = _internal_mutable_cmd_operator();
          ptr = ::PROTOBUF_NAMESPACE_ID::internal::InlineGreedyStringParser(str, ptr, ctx);
          CHK_(ptr);
        } else goto handle_unusual;
        continue;
      // int32 cmd = 2;
      case 2:
        if (PROTOBUF_PREDICT_TRUE(static_cast<::PROTOBUF_NAMESPACE_ID::uint8>(tag) == 16)) {
          cmd_ = ::PROTOBUF_NAMESPACE_ID::internal::ReadVarint64(&ptr);
          CHK_(ptr);
        } else goto handle_unusual;
        continue;
      // int32 world_id = 3;
      case 3:
        if (PROTOBUF_PREDICT_TRUE(static_cast<::PROTOBUF_NAMESPACE_ID::uint8>(tag) == 24)) {
          world_id_ = ::PROTOBUF_NAMESPACE_ID::internal::ReadVarint64(&ptr);
          CHK_(ptr);
        } else goto handle_unusual;
        continue;
      // bytes payload = 4;
      case 4:
        if (PROTOBUF_PREDICT_TRUE(static_cast<::PROTOBUF_NAMESPACE_ID::uint8>(tag) == 34)) {
          auto str = _internal_mutable_payload();
          ptr = ::PROTOBUF_NAMESPACE_ID::internal::InlineGreedyStringParser(str, ptr, ctx);
          CHK_(ptr);
        } else goto handle_unusual;
        continue;
      // int64 req_id = 5;
      case 5:
        if (PROTOBUF_PREDICT_TRUE(static_cast<::PROTOBUF_NAMESPACE_ID::uint8>(tag) == 40)) {
          req_id_ = ::PROTOBUF_NAMESPACE_ID::internal::ReadVarint64(&ptr);
          CHK_(ptr);
        } else goto handle_unusual;
        continue;
      default: {
      handle_unusual:
        if ((tag == 0) || ((tag & 7) == 4)) {
          CHK_(ptr);
          ctx->SetLastTag(tag);
          goto success;
        }
        ptr = UnknownFieldParse(tag,
            _internal_metadata_.mutable_unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(),
            ptr, ctx);
        CHK_(ptr != nullptr);
        continue;
      }
    }  // switch
  }  // while
success:
  return ptr;
failure:
  ptr = nullptr;
  goto success;
#undef CHK_
}

::PROTOBUF_NAMESPACE_ID::uint8* ReqCmdExecute::_InternalSerialize(
    ::PROTOBUF_NAMESPACE_ID::uint8* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const {
  // @@protoc_insertion_point(serialize_to_array_start:KWMsg.ReqCmdExecute)
  ::PROTOBUF_NAMESPACE_ID::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  // bytes cmd_operator = 1;
  if (!this->cmd_operator().empty()) {
    target = stream->WriteBytesMaybeAliased(
        1, this->_internal_cmd_operator(), target);
  }

  // int32 cmd = 2;
  if (this->cmd() != 0) {
    target = stream->EnsureSpace(target);
    target = ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::WriteInt32ToArray(2, this->_internal_cmd(), target);
  }

  // int32 world_id = 3;
  if (this->world_id() != 0) {
    target = stream->EnsureSpace(target);
    target = ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::WriteInt32ToArray(3, this->_internal_world_id(), target);
  }

  // bytes payload = 4;
  if (!this->payload().empty()) {
    target = stream->WriteBytesMaybeAliased(
        4, this->_internal_payload(), target);
  }

  // int64 req_id = 5;
  if (this->req_id() != 0) {
    target = stream->EnsureSpace(target);
    target = ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::WriteInt64ToArray(5, this->_internal_req_id(), target);
  }

  if (PROTOBUF_PREDICT_FALSE(_internal_metadata_.have_unknown_fields())) {
    target = ::PROTOBUF_NAMESPACE_ID::internal::WireFormat::InternalSerializeUnknownFieldsToArray(
        _internal_metadata_.unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(::PROTOBUF_NAMESPACE_ID::UnknownFieldSet::default_instance), target, stream);
  }
  // @@protoc_insertion_point(serialize_to_array_end:KWMsg.ReqCmdExecute)
  return target;
}

size_t ReqCmdExecute::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:KWMsg.ReqCmdExecute)
  size_t total_size = 0;

  ::PROTOBUF_NAMESPACE_ID::uint32 cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  // bytes cmd_operator = 1;
  if (!this->cmd_operator().empty()) {
    total_size += 1 +
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::BytesSize(
        this->_internal_cmd_operator());
  }

  // bytes payload = 4;
  if (!this->payload().empty()) {
    total_size += 1 +
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::BytesSize(
        this->_internal_payload());
  }

  // int32 cmd = 2;
  if (this->cmd() != 0) {
    total_size += 1 +
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::Int32Size(
        this->_internal_cmd());
  }

  // int32 world_id = 3;
  if (this->world_id() != 0) {
    total_size += 1 +
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::Int32Size(
        this->_internal_world_id());
  }

  // int64 req_id = 5;
  if (this->req_id() != 0) {
    total_size += 1 +
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::Int64Size(
        this->_internal_req_id());
  }

  if (PROTOBUF_PREDICT_FALSE(_internal_metadata_.have_unknown_fields())) {
    return ::PROTOBUF_NAMESPACE_ID::internal::ComputeUnknownFieldsSize(
        _internal_metadata_, total_size, &_cached_size_);
  }
  int cached_size = ::PROTOBUF_NAMESPACE_ID::internal::ToCachedSize(total_size);
  SetCachedSize(cached_size);
  return total_size;
}

void ReqCmdExecute::MergeFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) {
// @@protoc_insertion_point(generalized_merge_from_start:KWMsg.ReqCmdExecute)
  GOOGLE_DCHECK_NE(&from, this);
  const ReqCmdExecute* source =
      ::PROTOBUF_NAMESPACE_ID::DynamicCastToGenerated<ReqCmdExecute>(
          &from);
  if (source == nullptr) {
  // @@protoc_insertion_point(generalized_merge_from_cast_fail:KWMsg.ReqCmdExecute)
    ::PROTOBUF_NAMESPACE_ID::internal::ReflectionOps::Merge(from, this);
  } else {
  // @@protoc_insertion_point(generalized_merge_from_cast_success:KWMsg.ReqCmdExecute)
    MergeFrom(*source);
  }
}

void ReqCmdExecute::MergeFrom(const ReqCmdExecute& from) {
// @@protoc_insertion_point(class_specific_merge_from_start:KWMsg.ReqCmdExecute)
  GOOGLE_DCHECK_NE(&from, this);
  _internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
  ::PROTOBUF_NAMESPACE_ID::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  if (!from.cmd_operator().empty()) {
    _internal_set_cmd_operator(from._internal_cmd_operator());
  }
  if (!from.payload().empty()) {
    _internal_set_payload(from._internal_payload());
  }
  if (from.cmd() != 0) {
    _internal_set_cmd(from._internal_cmd());
  }
  if (from.world_id() != 0) {
    _internal_set_world_id(from._internal_world_id());
  }
  if (from.req_id() != 0) {
    _internal_set_req_id(from._internal_req_id());
  }
}

void ReqCmdExecute::CopyFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) {
// @@protoc_insertion_point(generalized_copy_from_start:KWMsg.ReqCmdExecute)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

void ReqCmdExecute::CopyFrom(const ReqCmdExecute& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:KWMsg.ReqCmdExecute)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool ReqCmdExecute::IsInitialized() const {
  return true;
}

void ReqCmdExecute::InternalSwap(ReqCmdExecute* other) {
  using std::swap;
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
  ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::InternalSwap(
      &::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(),
      &cmd_operator_, GetArenaForAllocation(),
      &other->cmd_operator_, other->GetArenaForAllocation()
  );
  ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::InternalSwap(
      &::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(),
      &payload_, GetArenaForAllocation(),
      &other->payload_, other->GetArenaForAllocation()
  );
  ::PROTOBUF_NAMESPACE_ID::internal::memswap<
      PROTOBUF_FIELD_OFFSET(ReqCmdExecute, req_id_)
      + sizeof(ReqCmdExecute::req_id_)
      - PROTOBUF_FIELD_OFFSET(ReqCmdExecute, cmd_)>(
          reinterpret_cast<char*>(&cmd_),
          reinterpret_cast<char*>(&other->cmd_));
}

::PROTOBUF_NAMESPACE_ID::Metadata ReqCmdExecute::GetMetadata() const {
  return ::PROTOBUF_NAMESPACE_ID::internal::AssignDescriptors(
      &descriptor_table_kwmsgcmd_2eproto_getter, &descriptor_table_kwmsgcmd_2eproto_once,
      file_level_metadata_kwmsgcmd_2eproto[0]);
}

// ===================================================================

class ReqGmGetPlayerData::_Internal {
 public:
};

ReqGmGetPlayerData::ReqGmGetPlayerData(::PROTOBUF_NAMESPACE_ID::Arena* arena)
  : ::PROTOBUF_NAMESPACE_ID::Message(arena),
  data_names_(arena) {
  SharedCtor();
  RegisterArenaDtor(arena);
  // @@protoc_insertion_point(arena_constructor:KWMsg.ReqGmGetPlayerData)
}
ReqGmGetPlayerData::ReqGmGetPlayerData(const ReqGmGetPlayerData& from)
  : ::PROTOBUF_NAMESPACE_ID::Message(),
      data_names_(from.data_names_) {
  _internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
  id_.UnsafeSetDefault(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited());
  if (!from._internal_id().empty()) {
    id_.Set(::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::EmptyDefault{}, from._internal_id(), 
      GetArenaForAllocation());
  }
  ::memcpy(&id_type_, &from.id_type_,
    static_cast<size_t>(reinterpret_cast<char*>(&req_id_) -
    reinterpret_cast<char*>(&id_type_)) + sizeof(req_id_));
  // @@protoc_insertion_point(copy_constructor:KWMsg.ReqGmGetPlayerData)
}

void ReqGmGetPlayerData::SharedCtor() {
id_.UnsafeSetDefault(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited());
::memset(reinterpret_cast<char*>(this) + static_cast<size_t>(
    reinterpret_cast<char*>(&id_type_) - reinterpret_cast<char*>(this)),
    0, static_cast<size_t>(reinterpret_cast<char*>(&req_id_) -
    reinterpret_cast<char*>(&id_type_)) + sizeof(req_id_));
}

ReqGmGetPlayerData::~ReqGmGetPlayerData() {
  // @@protoc_insertion_point(destructor:KWMsg.ReqGmGetPlayerData)
  SharedDtor();
  _internal_metadata_.Delete<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>();
}

void ReqGmGetPlayerData::SharedDtor() {
  GOOGLE_DCHECK(GetArenaForAllocation() == nullptr);
  id_.DestroyNoArena(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited());
}

void ReqGmGetPlayerData::ArenaDtor(void* object) {
  ReqGmGetPlayerData* _this = reinterpret_cast< ReqGmGetPlayerData* >(object);
  (void)_this;
}
void ReqGmGetPlayerData::RegisterArenaDtor(::PROTOBUF_NAMESPACE_ID::Arena*) {
}
void ReqGmGetPlayerData::SetCachedSize(int size) const {
  _cached_size_.Set(size);
}

void ReqGmGetPlayerData::Clear() {
// @@protoc_insertion_point(message_clear_start:KWMsg.ReqGmGetPlayerData)
  ::PROTOBUF_NAMESPACE_ID::uint32 cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  data_names_.Clear();
  id_.ClearToEmpty();
  ::memset(&id_type_, 0, static_cast<size_t>(
      reinterpret_cast<char*>(&req_id_) -
      reinterpret_cast<char*>(&id_type_)) + sizeof(req_id_));
  _internal_metadata_.Clear<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>();
}

const char* ReqGmGetPlayerData::_InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) {
#define CHK_(x) if (PROTOBUF_PREDICT_FALSE(!(x))) goto failure
  while (!ctx->Done(&ptr)) {
    ::PROTOBUF_NAMESPACE_ID::uint32 tag;
    ptr = ::PROTOBUF_NAMESPACE_ID::internal::ReadTag(ptr, &tag);
    switch (tag >> 3) {
      // bytes id = 1;
      case 1:
        if (PROTOBUF_PREDICT_TRUE(static_cast<::PROTOBUF_NAMESPACE_ID::uint8>(tag) == 10)) {
          auto str = _internal_mutable_id();
          ptr = ::PROTOBUF_NAMESPACE_ID::internal::InlineGreedyStringParser(str, ptr, ctx);
          CHK_(ptr);
        } else goto handle_unusual;
        continue;
      // .KWMsg.EGmGetPlayerDataIDType id_type = 2;
      case 2:
        if (PROTOBUF_PREDICT_TRUE(static_cast<::PROTOBUF_NAMESPACE_ID::uint8>(tag) == 16)) {
          ::PROTOBUF_NAMESPACE_ID::uint64 val = ::PROTOBUF_NAMESPACE_ID::internal::ReadVarint64(&ptr);
          CHK_(ptr);
          _internal_set_id_type(static_cast<::KWMsg::EGmGetPlayerDataIDType>(val));
        } else goto handle_unusual;
        continue;
      // .KWMsg.EGmGetPlayerDataType data_type = 3;
      case 3:
        if (PROTOBUF_PREDICT_TRUE(static_cast<::PROTOBUF_NAMESPACE_ID::uint8>(tag) == 24)) {
          ::PROTOBUF_NAMESPACE_ID::uint64 val = ::PROTOBUF_NAMESPACE_ID::internal::ReadVarint64(&ptr);
          CHK_(ptr);
          _internal_set_data_type(static_cast<::KWMsg::EGmGetPlayerDataType>(val));
        } else goto handle_unusual;
        continue;
      // int64 req_id = 4;
      case 4:
        if (PROTOBUF_PREDICT_TRUE(static_cast<::PROTOBUF_NAMESPACE_ID::uint8>(tag) == 32)) {
          req_id_ = ::PROTOBUF_NAMESPACE_ID::internal::ReadVarint64(&ptr);
          CHK_(ptr);
        } else goto handle_unusual;
        continue;
      // repeated bytes data_names = 5;
      case 5:
        if (PROTOBUF_PREDICT_TRUE(static_cast<::PROTOBUF_NAMESPACE_ID::uint8>(tag) == 42)) {
          ptr -= 1;
          do {
            ptr += 1;
            auto str = _internal_add_data_names();
            ptr = ::PROTOBUF_NAMESPACE_ID::internal::InlineGreedyStringParser(str, ptr, ctx);
            CHK_(ptr);
            if (!ctx->DataAvailable(ptr)) break;
          } while (::PROTOBUF_NAMESPACE_ID::internal::ExpectTag<42>(ptr));
        } else goto handle_unusual;
        continue;
      default: {
      handle_unusual:
        if ((tag == 0) || ((tag & 7) == 4)) {
          CHK_(ptr);
          ctx->SetLastTag(tag);
          goto success;
        }
        ptr = UnknownFieldParse(tag,
            _internal_metadata_.mutable_unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(),
            ptr, ctx);
        CHK_(ptr != nullptr);
        continue;
      }
    }  // switch
  }  // while
success:
  return ptr;
failure:
  ptr = nullptr;
  goto success;
#undef CHK_
}

::PROTOBUF_NAMESPACE_ID::uint8* ReqGmGetPlayerData::_InternalSerialize(
    ::PROTOBUF_NAMESPACE_ID::uint8* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const {
  // @@protoc_insertion_point(serialize_to_array_start:KWMsg.ReqGmGetPlayerData)
  ::PROTOBUF_NAMESPACE_ID::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  // bytes id = 1;
  if (!this->id().empty()) {
    target = stream->WriteBytesMaybeAliased(
        1, this->_internal_id(), target);
  }

  // .KWMsg.EGmGetPlayerDataIDType id_type = 2;
  if (this->id_type() != 0) {
    target = stream->EnsureSpace(target);
    target = ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::WriteEnumToArray(
      2, this->_internal_id_type(), target);
  }

  // .KWMsg.EGmGetPlayerDataType data_type = 3;
  if (this->data_type() != 0) {
    target = stream->EnsureSpace(target);
    target = ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::WriteEnumToArray(
      3, this->_internal_data_type(), target);
  }

  // int64 req_id = 4;
  if (this->req_id() != 0) {
    target = stream->EnsureSpace(target);
    target = ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::WriteInt64ToArray(4, this->_internal_req_id(), target);
  }

  // repeated bytes data_names = 5;
  for (int i = 0, n = this->_internal_data_names_size(); i < n; i++) {
    const auto& s = this->_internal_data_names(i);
    target = stream->WriteBytes(5, s, target);
  }

  if (PROTOBUF_PREDICT_FALSE(_internal_metadata_.have_unknown_fields())) {
    target = ::PROTOBUF_NAMESPACE_ID::internal::WireFormat::InternalSerializeUnknownFieldsToArray(
        _internal_metadata_.unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(::PROTOBUF_NAMESPACE_ID::UnknownFieldSet::default_instance), target, stream);
  }
  // @@protoc_insertion_point(serialize_to_array_end:KWMsg.ReqGmGetPlayerData)
  return target;
}

size_t ReqGmGetPlayerData::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:KWMsg.ReqGmGetPlayerData)
  size_t total_size = 0;

  ::PROTOBUF_NAMESPACE_ID::uint32 cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  // repeated bytes data_names = 5;
  total_size += 1 *
      ::PROTOBUF_NAMESPACE_ID::internal::FromIntSize(data_names_.size());
  for (int i = 0, n = data_names_.size(); i < n; i++) {
    total_size += ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::BytesSize(
      data_names_.Get(i));
  }

  // bytes id = 1;
  if (!this->id().empty()) {
    total_size += 1 +
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::BytesSize(
        this->_internal_id());
  }

  // .KWMsg.EGmGetPlayerDataIDType id_type = 2;
  if (this->id_type() != 0) {
    total_size += 1 +
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::EnumSize(this->_internal_id_type());
  }

  // .KWMsg.EGmGetPlayerDataType data_type = 3;
  if (this->data_type() != 0) {
    total_size += 1 +
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::EnumSize(this->_internal_data_type());
  }

  // int64 req_id = 4;
  if (this->req_id() != 0) {
    total_size += 1 +
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::Int64Size(
        this->_internal_req_id());
  }

  if (PROTOBUF_PREDICT_FALSE(_internal_metadata_.have_unknown_fields())) {
    return ::PROTOBUF_NAMESPACE_ID::internal::ComputeUnknownFieldsSize(
        _internal_metadata_, total_size, &_cached_size_);
  }
  int cached_size = ::PROTOBUF_NAMESPACE_ID::internal::ToCachedSize(total_size);
  SetCachedSize(cached_size);
  return total_size;
}

void ReqGmGetPlayerData::MergeFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) {
// @@protoc_insertion_point(generalized_merge_from_start:KWMsg.ReqGmGetPlayerData)
  GOOGLE_DCHECK_NE(&from, this);
  const ReqGmGetPlayerData* source =
      ::PROTOBUF_NAMESPACE_ID::DynamicCastToGenerated<ReqGmGetPlayerData>(
          &from);
  if (source == nullptr) {
  // @@protoc_insertion_point(generalized_merge_from_cast_fail:KWMsg.ReqGmGetPlayerData)
    ::PROTOBUF_NAMESPACE_ID::internal::ReflectionOps::Merge(from, this);
  } else {
  // @@protoc_insertion_point(generalized_merge_from_cast_success:KWMsg.ReqGmGetPlayerData)
    MergeFrom(*source);
  }
}

void ReqGmGetPlayerData::MergeFrom(const ReqGmGetPlayerData& from) {
// @@protoc_insertion_point(class_specific_merge_from_start:KWMsg.ReqGmGetPlayerData)
  GOOGLE_DCHECK_NE(&from, this);
  _internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
  ::PROTOBUF_NAMESPACE_ID::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  data_names_.MergeFrom(from.data_names_);
  if (!from.id().empty()) {
    _internal_set_id(from._internal_id());
  }
  if (from.id_type() != 0) {
    _internal_set_id_type(from._internal_id_type());
  }
  if (from.data_type() != 0) {
    _internal_set_data_type(from._internal_data_type());
  }
  if (from.req_id() != 0) {
    _internal_set_req_id(from._internal_req_id());
  }
}

void ReqGmGetPlayerData::CopyFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) {
// @@protoc_insertion_point(generalized_copy_from_start:KWMsg.ReqGmGetPlayerData)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

void ReqGmGetPlayerData::CopyFrom(const ReqGmGetPlayerData& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:KWMsg.ReqGmGetPlayerData)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool ReqGmGetPlayerData::IsInitialized() const {
  return true;
}

void ReqGmGetPlayerData::InternalSwap(ReqGmGetPlayerData* other) {
  using std::swap;
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
  data_names_.InternalSwap(&other->data_names_);
  ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::InternalSwap(
      &::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(),
      &id_, GetArenaForAllocation(),
      &other->id_, other->GetArenaForAllocation()
  );
  ::PROTOBUF_NAMESPACE_ID::internal::memswap<
      PROTOBUF_FIELD_OFFSET(ReqGmGetPlayerData, req_id_)
      + sizeof(ReqGmGetPlayerData::req_id_)
      - PROTOBUF_FIELD_OFFSET(ReqGmGetPlayerData, id_type_)>(
          reinterpret_cast<char*>(&id_type_),
          reinterpret_cast<char*>(&other->id_type_));
}

::PROTOBUF_NAMESPACE_ID::Metadata ReqGmGetPlayerData::GetMetadata() const {
  return ::PROTOBUF_NAMESPACE_ID::internal::AssignDescriptors(
      &descriptor_table_kwmsgcmd_2eproto_getter, &descriptor_table_kwmsgcmd_2eproto_once,
      file_level_metadata_kwmsgcmd_2eproto[1]);
}

// ===================================================================

class AckGmGetPlayerData::_Internal {
 public:
};

AckGmGetPlayerData::AckGmGetPlayerData(::PROTOBUF_NAMESPACE_ID::Arena* arena)
  : ::PROTOBUF_NAMESPACE_ID::Message(arena),
  data_names_(arena),
  data_values_(arena) {
  SharedCtor();
  RegisterArenaDtor(arena);
  // @@protoc_insertion_point(arena_constructor:KWMsg.AckGmGetPlayerData)
}
AckGmGetPlayerData::AckGmGetPlayerData(const AckGmGetPlayerData& from)
  : ::PROTOBUF_NAMESPACE_ID::Message(),
      data_names_(from.data_names_),
      data_values_(from.data_values_) {
  _internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
  id_.UnsafeSetDefault(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited());
  if (!from._internal_id().empty()) {
    id_.Set(::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::EmptyDefault{}, from._internal_id(), 
      GetArenaForAllocation());
  }
  ::memcpy(&req_id_, &from.req_id_,
    static_cast<size_t>(reinterpret_cast<char*>(&ret_type_) -
    reinterpret_cast<char*>(&req_id_)) + sizeof(ret_type_));
  // @@protoc_insertion_point(copy_constructor:KWMsg.AckGmGetPlayerData)
}

void AckGmGetPlayerData::SharedCtor() {
id_.UnsafeSetDefault(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited());
::memset(reinterpret_cast<char*>(this) + static_cast<size_t>(
    reinterpret_cast<char*>(&req_id_) - reinterpret_cast<char*>(this)),
    0, static_cast<size_t>(reinterpret_cast<char*>(&ret_type_) -
    reinterpret_cast<char*>(&req_id_)) + sizeof(ret_type_));
}

AckGmGetPlayerData::~AckGmGetPlayerData() {
  // @@protoc_insertion_point(destructor:KWMsg.AckGmGetPlayerData)
  SharedDtor();
  _internal_metadata_.Delete<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>();
}

void AckGmGetPlayerData::SharedDtor() {
  GOOGLE_DCHECK(GetArenaForAllocation() == nullptr);
  id_.DestroyNoArena(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited());
}

void AckGmGetPlayerData::ArenaDtor(void* object) {
  AckGmGetPlayerData* _this = reinterpret_cast< AckGmGetPlayerData* >(object);
  (void)_this;
}
void AckGmGetPlayerData::RegisterArenaDtor(::PROTOBUF_NAMESPACE_ID::Arena*) {
}
void AckGmGetPlayerData::SetCachedSize(int size) const {
  _cached_size_.Set(size);
}

void AckGmGetPlayerData::Clear() {
// @@protoc_insertion_point(message_clear_start:KWMsg.AckGmGetPlayerData)
  ::PROTOBUF_NAMESPACE_ID::uint32 cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  data_names_.Clear();
  data_values_.Clear();
  id_.ClearToEmpty();
  ::memset(&req_id_, 0, static_cast<size_t>(
      reinterpret_cast<char*>(&ret_type_) -
      reinterpret_cast<char*>(&req_id_)) + sizeof(ret_type_));
  _internal_metadata_.Clear<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>();
}

const char* AckGmGetPlayerData::_InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) {
#define CHK_(x) if (PROTOBUF_PREDICT_FALSE(!(x))) goto failure
  while (!ctx->Done(&ptr)) {
    ::PROTOBUF_NAMESPACE_ID::uint32 tag;
    ptr = ::PROTOBUF_NAMESPACE_ID::internal::ReadTag(ptr, &tag);
    switch (tag >> 3) {
      // bytes id = 1;
      case 1:
        if (PROTOBUF_PREDICT_TRUE(static_cast<::PROTOBUF_NAMESPACE_ID::uint8>(tag) == 10)) {
          auto str = _internal_mutable_id();
          ptr = ::PROTOBUF_NAMESPACE_ID::internal::InlineGreedyStringParser(str, ptr, ctx);
          CHK_(ptr);
        } else goto handle_unusual;
        continue;
      // .KWMsg.EGmGetPlayerDataIDType id_type = 2;
      case 2:
        if (PROTOBUF_PREDICT_TRUE(static_cast<::PROTOBUF_NAMESPACE_ID::uint8>(tag) == 16)) {
          ::PROTOBUF_NAMESPACE_ID::uint64 val = ::PROTOBUF_NAMESPACE_ID::internal::ReadVarint64(&ptr);
          CHK_(ptr);
          _internal_set_id_type(static_cast<::KWMsg::EGmGetPlayerDataIDType>(val));
        } else goto handle_unusual;
        continue;
      // int64 req_id = 3;
      case 3:
        if (PROTOBUF_PREDICT_TRUE(static_cast<::PROTOBUF_NAMESPACE_ID::uint8>(tag) == 24)) {
          req_id_ = ::PROTOBUF_NAMESPACE_ID::internal::ReadVarint64(&ptr);
          CHK_(ptr);
        } else goto handle_unusual;
        continue;
      // .KWMsg.EGmGetPlayerDataType data_type = 4;
      case 4:
        if (PROTOBUF_PREDICT_TRUE(static_cast<::PROTOBUF_NAMESPACE_ID::uint8>(tag) == 32)) {
          ::PROTOBUF_NAMESPACE_ID::uint64 val = ::PROTOBUF_NAMESPACE_ID::internal::ReadVarint64(&ptr);
          CHK_(ptr);
          _internal_set_data_type(static_cast<::KWMsg::EGmGetPlayerDataType>(val));
        } else goto handle_unusual;
        continue;
      // .KWMsg.EAckGmGetPlayerDataRetType ret_type = 5;
      case 5:
        if (PROTOBUF_PREDICT_TRUE(static_cast<::PROTOBUF_NAMESPACE_ID::uint8>(tag) == 40)) {
          ::PROTOBUF_NAMESPACE_ID::uint64 val = ::PROTOBUF_NAMESPACE_ID::internal::ReadVarint64(&ptr);
          CHK_(ptr);
          _internal_set_ret_type(static_cast<::KWMsg::EAckGmGetPlayerDataRetType>(val));
        } else goto handle_unusual;
        continue;
      // repeated bytes data_names = 6;
      case 6:
        if (PROTOBUF_PREDICT_TRUE(static_cast<::PROTOBUF_NAMESPACE_ID::uint8>(tag) == 50)) {
          ptr -= 1;
          do {
            ptr += 1;
            auto str = _internal_add_data_names();
            ptr = ::PROTOBUF_NAMESPACE_ID::internal::InlineGreedyStringParser(str, ptr, ctx);
            CHK_(ptr);
            if (!ctx->DataAvailable(ptr)) break;
          } while (::PROTOBUF_NAMESPACE_ID::internal::ExpectTag<50>(ptr));
        } else goto handle_unusual;
        continue;
      // repeated bytes data_values = 7;
      case 7:
        if (PROTOBUF_PREDICT_TRUE(static_cast<::PROTOBUF_NAMESPACE_ID::uint8>(tag) == 58)) {
          ptr -= 1;
          do {
            ptr += 1;
            auto str = _internal_add_data_values();
            ptr = ::PROTOBUF_NAMESPACE_ID::internal::InlineGreedyStringParser(str, ptr, ctx);
            CHK_(ptr);
            if (!ctx->DataAvailable(ptr)) break;
          } while (::PROTOBUF_NAMESPACE_ID::internal::ExpectTag<58>(ptr));
        } else goto handle_unusual;
        continue;
      default: {
      handle_unusual:
        if ((tag == 0) || ((tag & 7) == 4)) {
          CHK_(ptr);
          ctx->SetLastTag(tag);
          goto success;
        }
        ptr = UnknownFieldParse(tag,
            _internal_metadata_.mutable_unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(),
            ptr, ctx);
        CHK_(ptr != nullptr);
        continue;
      }
    }  // switch
  }  // while
success:
  return ptr;
failure:
  ptr = nullptr;
  goto success;
#undef CHK_
}

::PROTOBUF_NAMESPACE_ID::uint8* AckGmGetPlayerData::_InternalSerialize(
    ::PROTOBUF_NAMESPACE_ID::uint8* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const {
  // @@protoc_insertion_point(serialize_to_array_start:KWMsg.AckGmGetPlayerData)
  ::PROTOBUF_NAMESPACE_ID::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  // bytes id = 1;
  if (!this->id().empty()) {
    target = stream->WriteBytesMaybeAliased(
        1, this->_internal_id(), target);
  }

  // .KWMsg.EGmGetPlayerDataIDType id_type = 2;
  if (this->id_type() != 0) {
    target = stream->EnsureSpace(target);
    target = ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::WriteEnumToArray(
      2, this->_internal_id_type(), target);
  }

  // int64 req_id = 3;
  if (this->req_id() != 0) {
    target = stream->EnsureSpace(target);
    target = ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::WriteInt64ToArray(3, this->_internal_req_id(), target);
  }

  // .KWMsg.EGmGetPlayerDataType data_type = 4;
  if (this->data_type() != 0) {
    target = stream->EnsureSpace(target);
    target = ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::WriteEnumToArray(
      4, this->_internal_data_type(), target);
  }

  // .KWMsg.EAckGmGetPlayerDataRetType ret_type = 5;
  if (this->ret_type() != 0) {
    target = stream->EnsureSpace(target);
    target = ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::WriteEnumToArray(
      5, this->_internal_ret_type(), target);
  }

  // repeated bytes data_names = 6;
  for (int i = 0, n = this->_internal_data_names_size(); i < n; i++) {
    const auto& s = this->_internal_data_names(i);
    target = stream->WriteBytes(6, s, target);
  }

  // repeated bytes data_values = 7;
  for (int i = 0, n = this->_internal_data_values_size(); i < n; i++) {
    const auto& s = this->_internal_data_values(i);
    target = stream->WriteBytes(7, s, target);
  }

  if (PROTOBUF_PREDICT_FALSE(_internal_metadata_.have_unknown_fields())) {
    target = ::PROTOBUF_NAMESPACE_ID::internal::WireFormat::InternalSerializeUnknownFieldsToArray(
        _internal_metadata_.unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(::PROTOBUF_NAMESPACE_ID::UnknownFieldSet::default_instance), target, stream);
  }
  // @@protoc_insertion_point(serialize_to_array_end:KWMsg.AckGmGetPlayerData)
  return target;
}

size_t AckGmGetPlayerData::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:KWMsg.AckGmGetPlayerData)
  size_t total_size = 0;

  ::PROTOBUF_NAMESPACE_ID::uint32 cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  // repeated bytes data_names = 6;
  total_size += 1 *
      ::PROTOBUF_NAMESPACE_ID::internal::FromIntSize(data_names_.size());
  for (int i = 0, n = data_names_.size(); i < n; i++) {
    total_size += ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::BytesSize(
      data_names_.Get(i));
  }

  // repeated bytes data_values = 7;
  total_size += 1 *
      ::PROTOBUF_NAMESPACE_ID::internal::FromIntSize(data_values_.size());
  for (int i = 0, n = data_values_.size(); i < n; i++) {
    total_size += ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::BytesSize(
      data_values_.Get(i));
  }

  // bytes id = 1;
  if (!this->id().empty()) {
    total_size += 1 +
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::BytesSize(
        this->_internal_id());
  }

  // int64 req_id = 3;
  if (this->req_id() != 0) {
    total_size += 1 +
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::Int64Size(
        this->_internal_req_id());
  }

  // .KWMsg.EGmGetPlayerDataIDType id_type = 2;
  if (this->id_type() != 0) {
    total_size += 1 +
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::EnumSize(this->_internal_id_type());
  }

  // .KWMsg.EGmGetPlayerDataType data_type = 4;
  if (this->data_type() != 0) {
    total_size += 1 +
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::EnumSize(this->_internal_data_type());
  }

  // .KWMsg.EAckGmGetPlayerDataRetType ret_type = 5;
  if (this->ret_type() != 0) {
    total_size += 1 +
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::EnumSize(this->_internal_ret_type());
  }

  if (PROTOBUF_PREDICT_FALSE(_internal_metadata_.have_unknown_fields())) {
    return ::PROTOBUF_NAMESPACE_ID::internal::ComputeUnknownFieldsSize(
        _internal_metadata_, total_size, &_cached_size_);
  }
  int cached_size = ::PROTOBUF_NAMESPACE_ID::internal::ToCachedSize(total_size);
  SetCachedSize(cached_size);
  return total_size;
}

void AckGmGetPlayerData::MergeFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) {
// @@protoc_insertion_point(generalized_merge_from_start:KWMsg.AckGmGetPlayerData)
  GOOGLE_DCHECK_NE(&from, this);
  const AckGmGetPlayerData* source =
      ::PROTOBUF_NAMESPACE_ID::DynamicCastToGenerated<AckGmGetPlayerData>(
          &from);
  if (source == nullptr) {
  // @@protoc_insertion_point(generalized_merge_from_cast_fail:KWMsg.AckGmGetPlayerData)
    ::PROTOBUF_NAMESPACE_ID::internal::ReflectionOps::Merge(from, this);
  } else {
  // @@protoc_insertion_point(generalized_merge_from_cast_success:KWMsg.AckGmGetPlayerData)
    MergeFrom(*source);
  }
}

void AckGmGetPlayerData::MergeFrom(const AckGmGetPlayerData& from) {
// @@protoc_insertion_point(class_specific_merge_from_start:KWMsg.AckGmGetPlayerData)
  GOOGLE_DCHECK_NE(&from, this);
  _internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
  ::PROTOBUF_NAMESPACE_ID::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  data_names_.MergeFrom(from.data_names_);
  data_values_.MergeFrom(from.data_values_);
  if (!from.id().empty()) {
    _internal_set_id(from._internal_id());
  }
  if (from.req_id() != 0) {
    _internal_set_req_id(from._internal_req_id());
  }
  if (from.id_type() != 0) {
    _internal_set_id_type(from._internal_id_type());
  }
  if (from.data_type() != 0) {
    _internal_set_data_type(from._internal_data_type());
  }
  if (from.ret_type() != 0) {
    _internal_set_ret_type(from._internal_ret_type());
  }
}

void AckGmGetPlayerData::CopyFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) {
// @@protoc_insertion_point(generalized_copy_from_start:KWMsg.AckGmGetPlayerData)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

void AckGmGetPlayerData::CopyFrom(const AckGmGetPlayerData& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:KWMsg.AckGmGetPlayerData)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool AckGmGetPlayerData::IsInitialized() const {
  return true;
}

void AckGmGetPlayerData::InternalSwap(AckGmGetPlayerData* other) {
  using std::swap;
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
  data_names_.InternalSwap(&other->data_names_);
  data_values_.InternalSwap(&other->data_values_);
  ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::InternalSwap(
      &::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(),
      &id_, GetArenaForAllocation(),
      &other->id_, other->GetArenaForAllocation()
  );
  ::PROTOBUF_NAMESPACE_ID::internal::memswap<
      PROTOBUF_FIELD_OFFSET(AckGmGetPlayerData, ret_type_)
      + sizeof(AckGmGetPlayerData::ret_type_)
      - PROTOBUF_FIELD_OFFSET(AckGmGetPlayerData, req_id_)>(
          reinterpret_cast<char*>(&req_id_),
          reinterpret_cast<char*>(&other->req_id_));
}

::PROTOBUF_NAMESPACE_ID::Metadata AckGmGetPlayerData::GetMetadata() const {
  return ::PROTOBUF_NAMESPACE_ID::internal::AssignDescriptors(
      &descriptor_table_kwmsgcmd_2eproto_getter, &descriptor_table_kwmsgcmd_2eproto_once,
      file_level_metadata_kwmsgcmd_2eproto[2]);
}

// @@protoc_insertion_point(namespace_scope)
}  // namespace KWMsg
PROTOBUF_NAMESPACE_OPEN
template<> PROTOBUF_NOINLINE ::KWMsg::ReqCmdExecute* Arena::CreateMaybeMessage< ::KWMsg::ReqCmdExecute >(Arena* arena) {
  return Arena::CreateMessageInternal< ::KWMsg::ReqCmdExecute >(arena);
}
template<> PROTOBUF_NOINLINE ::KWMsg::ReqGmGetPlayerData* Arena::CreateMaybeMessage< ::KWMsg::ReqGmGetPlayerData >(Arena* arena) {
  return Arena::CreateMessageInternal< ::KWMsg::ReqGmGetPlayerData >(arena);
}
template<> PROTOBUF_NOINLINE ::KWMsg::AckGmGetPlayerData* Arena::CreateMaybeMessage< ::KWMsg::AckGmGetPlayerData >(Arena* arena) {
  return Arena::CreateMessageInternal< ::KWMsg::AckGmGetPlayerData >(arena);
}
PROTOBUF_NAMESPACE_CLOSE

// @@protoc_insertion_point(global_scope)
#include <google/protobuf/port_undef.inc>
