[server]
port = 9099

[log]
logpath = './log/'
logname = 'gin'
loglevel = 3
maxnum=20
maxsize=10000000

[database]
host = "127.0.0.1"
port = 3306
user = "root"
password = ""
dbname = "ingame_test"
conn_num = 100
charset="utf8mb4"
