# nacos-consumer

server:
  port: 8882

spring:
  application:
    name: nacos-consumer
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848
    sentinel:
      transport:
        dashboard: localhost:8080
      eager: true

feign:
  sentinel:
    enabled: true
